#!/usr/bin/env node

"use strict";

const process = require("node:process");
const path = require("node:path");

const BASE_PATH = path.join(__dirname);

const DistributeDarwinArm64 = require(path.join(BASE_PATH, "deploy_app", "macOS-arm64-dmg", "package_dmg"));


function runCommand(command, afterDoing = () => 0) {
    console.log("正在执行：" + command);
    let exec = require('child_process').exec;
    exec(command, function (err, stdout, stderr) {
        if (err) {
            console.log('error:' + stderr);
        } else {
            console.log(stdout);
            afterDoing();
        }
    });
}

let distributeDarwinArm64 = new DistributeDarwinArm64();

// 开始打包应用
console.log(`检测到系统架构：${ process.arch }...`);
if (process.platform === "win32") {
    console.log("检测到操作系统：Windows...");
    runCommand(`cd ${BASE_PATH} && npm run package`, () => {
        console.log("软件编译完成，现在可以使用Inno Setup进行打包了。");
    });
}

if (process.platform === "darwin") {
    console.log("检测到操作系统：macOS...");
    distributeDarwinArm64.run();
}

if (process.platform === "linux") {
    console.log("检测到操作系统：Linux...");
    runCommand(`cd ${BASE_PATH} && npm run package`, () => 0);
}
