#!/usr/bin/env node

"use strict";

const process = require("node:process");
const path = require("node:path");

const BASE_PATH = path.join(__dirname);

const DistributeWin32X64 = require(path.join(BASE_PATH, "deploy_app", "Windows-x64-msi", "gen_config_msi"));
const DistributeDarwinArm64 = require(path.join(BASE_PATH, "deploy_app", "macOS-arm64-dmg", "package_dmg"));


function runCommand(command, afterDoing = () => 0) {
    console.log("正在执行：" + command);
    let exec = require('child_process').exec;
    exec(command, function (err, stdout, stderr) {
        if (err) {
            console.log('error:' + stderr);
        } else {
            console.log(stdout);
            afterDoing();
        }
    });
}

let distributeWin32X64 = new DistributeWin32X64();
let distributeDarwinArm64 = new DistributeDarwinArm64();

// 开始打包应用
console.log(`检测到系统架构：${ process.arch }...`);
if (process.platform === "win32") {
    console.log("检测到操作系统：Windows...");
    if (process.arch === "x64-ah") distributeWin32X64.run();
    else if (process.arch === "arm64-ah") runCommand(`cd ${BASE_PATH}; npm run package`, () => 0);
}

if (process.platform === "darwin") {
    console.log("检测到操作系统：macOS...");
    distributeDarwinArm64.run();
}

if (process.platform === "linux") {
    console.log("检测到操作系统：Linux...");
    runCommand(`cd ${BASE_PATH} && npm run package`, () => 0);
}

