"use strict";

const {FusesPlugin} = require('@electron-forge/plugin-fuses');
const {FuseV1Options, FuseVersion} = require('@electron/fuses');
const path = require("node:path");


module.exports = {
    packagerConfig: {
        asar: true,
        // extraResource: [
        //     path.join(__dirname, './libs/rust_libraries')
        // ],
        overwrite: true,
        // download: {
        //     mirror: `file://${path.join(__dirname, './electron-cache/')}`,
        //     cache: path.join(__dirname, './electron-cache/'),
        //     force: false,
        // },
        // electronZipDir: path.join(__dirname, './electron-cache/electron/36.1.0/'),
        ignore: [
            "deploy_app",
            ".git",
            ".vscode",
            ".idea",
            ".gitignore",
            "distribute",
            "README.md",
            "test.md",
            "electron-cache",
            "examples",
            "package-lock.json",
            "node_modules",

            "libs/node-libs",
            "libs/third_party/mermaid/dist/__mocks__",
            "libs/third_party/mermaid/dist/dagre-wrapper",
            "libs/third_party/mermaid/dist/diagram-api",
            "libs/third_party/mermaid/dist/diagrams",
            "libs/third_party/mermaid/dist/docs",
            "libs/third_party/mermaid/dist/rendering-util",
            "libs/third_party/mermaid/dist/tests",
            "libs/third_party/mermaid/dist/themes",
            "libs/third_party/mermaid/dist/utils",
            "libs/third_party/mermaid/dist/accessibility.d.ts",
            "libs/third_party/mermaid/dist/accessibility.spec.d.ts",
            "libs/third_party/mermaid/dist/assignWithDepth.d.ts",
            "libs/third_party/mermaid/dist/config.d.ts",
            "libs/third_party/mermaid/dist/config.spec.d.ts",
            "libs/third_party/mermaid/dist/config.type.d.ts",
            "libs/third_party/mermaid/dist/defaultConfig.d.ts",
            "libs/third_party/mermaid/dist/Diagram.d.ts",
            "libs/third_party/mermaid/dist/diagram.spec.d.ts",
            "libs/third_party/mermaid/dist/errors.d.ts",
            "libs/third_party/mermaid/dist/interactionDb.d.ts",
            "libs/third_party/mermaid/dist/internals.d.ts",
            "libs/third_party/mermaid/dist/logger.d.ts",
            "libs/third_party/mermaid/dist/mermaid.d.ts",
            "libs/third_party/mermaid/dist/mermaid.spec.d.ts",
            "libs/third_party/mermaid/dist/mermaidAPI.d.ts",
            "libs/third_party/mermaid/dist/mermaidAPI.spec.d.ts",
            "libs/third_party/mermaid/dist/preprocess.d.ts",
            "libs/third_party/mermaid/dist/setupGraphViewbox.d.ts",
            "libs/third_party/mermaid/dist/styles.d.ts",
            "libs/third_party/mermaid/dist/styles.spec.d.ts",
            "libs/third_party/mermaid/dist/types.d.ts",
            "libs/third_party/mermaid/dist/utils.d.ts",
            "libs/third_party/mermaid/dist/utils.spec.d.ts",

            "libs/third_party/monaco/CHANGELOG.md",
            "libs/third_party/monaco/dev",
            "libs/third_party/monaco/esm",
            "libs/third_party/monaco/LICENSE",
            "libs/third_party/monaco/min-maps",
            "libs/third_party/monaco/monaco.d.ts",
            "libs/third_party/monaco/package.json",
            "libs/third_party/monaco/README.md",
            "libs/third_party/monaco/ThirdPartyNotices.txt",

            "libs/xc_mdz",

            "libs/third_party/monaco/dev/vs/base/worker/workerMain.js.map",
            "libs/third_party/monaco/dev/vs/editor/editor.main.js.map",
            "libs/third_party/monaco/min-maps/vs/loader.js.map",
            "libs/third_party/monaco/min-maps/vs/base/worker/workerMain.js.map",
            "libs/third_party/monaco/min-maps/vs/editor/editor.main.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.zh-cn.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.es.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.de.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.ru.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.it.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.fr.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.ko.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.ja.js.map",
            "libs/third_party/monaco/min-maps/nls.messages.zh-tw.js.map",
            "libs/third_party/mermaid/dist/mermaid.esm.min.mjs.map",
            "libs/third_party/mermaid/dist/mermaid.js.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-S67DUUA5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/timeline-definition-VFFECQCT.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-ZN7TASNU.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/ganttDiagram-5MLOKHXO.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-USR3SDWQ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/xychartDiagram-4C6ER3FX.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-HQLFZTFY.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/katex-SWYD7GD6.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/diagram-R7SGKMCD.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-QTJCGBHB.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/kanban-definition-4PSEFK7X.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/stateDiagram-v2-NOSC7VFN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/dagre-J4RCDQSV.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-L736DJ4U.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-FASC7IG4.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-5ZJXQJOJ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-MBJCTAW2.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/quadrantDiagram-KBTC774P.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-MEBTFSOL.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/sankeyDiagram-2NKXCTV4.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-GTKDMUJJ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-SWO474TD.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-6BY5RJGC.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/flowDiagram-RXJ4TZVH.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-7LIB5WBN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-2VPXETT4.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-VSLJSFIP.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/stateDiagram-76M766UR.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/erDiagram-K5RJBHCA.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/journeyDiagram-UZIDTGLP.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-RRF4A5XS.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/sequenceDiagram-ODO66PDE.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-IO347I67.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-D7JRX7UM.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/classDiagram-v2-PRA2ZCF7.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-LM6QDVU5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/gitGraphDiagram-WO7WVN2C.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/mindmap-definition-RP2J3NYQ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/gitGraph-O2Q2CXLX-CIPL3GNK.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/packet-KVYON367-D24LN7JZ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-4KE642ED.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-DDW4HWGY.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-NA3436M7.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-ZKYS2E5M.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/architecture-4AB2E3PP-7QDGZQEU.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/info-4N47QTOZ-2BEI6D6A.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-YM3XIQPS.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/blockDiagram-GQNB4GIR.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/pieDiagram-Q56JBFDI.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-TYETAW3D.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/architectureDiagram-YZ6UH2CF.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/infoDiagram-E3C2IIUA.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/pie-R6RNRRYF-FUPP6FTN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-237OD7E6.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-YPUTD6PB.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-JVB3IFOF.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-ZWYQHTDX.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/c4Diagram-GNV6VVOW.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/diagram-7BLTIMBB.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/classDiagram-MKYM2BOE.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-HESFG3RP.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-DLZS2ZFX.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/requirementDiagram-OPD2HUS5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-TI4EEUUG.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/chunk-SHLHLJRN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm.min/radar-MK3ICKWK-KPFLJ5ZN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/pieDiagram-FPR3CNQC.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-GKOISANM.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/radar-MK3ICKWK-55CS4JTO.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/journeyDiagram-VHRN44N3.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-GRZAG2UZ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/pie-R6RNRRYF-7FBZ26YS.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/packet-KVYON367-WYA4Q6SA.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-SDBY772Q.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-CRQPXCKQ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/katex-5N2NCDMP.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/gitGraphDiagram-XHLTLO3W.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/erDiagram-AK44R45H.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/architecture-4AB2E3PP-NSNL5AAT.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-Q7X626QO.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-TGZYFRKZ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/requirementDiagram-P5NVWGNK.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/xychartDiagram-674MFTBU.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-ZVRJXRH7.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-7JTU5PD2.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/sankeyDiagram-C6NZRJHT.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-3L32CQKD.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-XIYN7VYH.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/c4Diagram-6R2MQUNL.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-EOAU2GW5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/classDiagram-LB37KKQG.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/timeline-definition-65575674.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/stateDiagram-WI5ZVJ5I.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/dagre-CMTPJJKG.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-CCYIEPPW.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/stateDiagram-v2-KVDSFUFK.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-STFVS7YW.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/diagram-BIPOGRU5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/kanban-definition-K5J3OUUV.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/info-4N47QTOZ-ZOHCZVQH.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/gitGraph-O2Q2CXLX-J735MULX.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-YFKFDTKC.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-R4WPHL2B.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-VKJI5BFR.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-DLQEHMXD.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/ganttDiagram-H5QQZTZ5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-K2ZEYYM2.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-H62MP5RN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-4AQQYWZS.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/architectureDiagram-RWNHDUBN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-YIX7P6T4.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-OTG2ZAWT.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-EFPBJHX4.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-5EMSI65K.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-W3YOBQ4T.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-SVWLYT5M.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/classDiagram-v2-KFQJBC22.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/infoDiagram-TP2HPDHO.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-IHYUGLNO.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-T2M37SMK.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/mindmap-definition-TI5ONXTW.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-AGEMWPJR.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/quadrantDiagram-RLP5YTJ2.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/blockDiagram-XZSR5OGQ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/flowDiagram-XARHJDSH.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/diagram-YF4VECWA.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-YJGJQOYZ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-HD3LK5B5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/sequenceDiagram-6SLVIXKN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-COUQ6RZ3.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-GTV5PL3S.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.esm/chunk-Q7VUVKE6.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/infoDiagram-PH2N3AL5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/erDiagram-Q7BY3M3F.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-6JRP7KZX.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/diagram-SSKATNLV.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/xychartDiagram-VJFVF3MP.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/architectureDiagram-IEHRJDOE.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/blockDiagram-JOT3LUYC.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/ganttDiagram-APWFNJXF.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/classDiagram-GIVACNV2.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-5NNNAHNI.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/journeyDiagram-U35MCT3I.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-H2D2JQ3I.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-RZ5BOZE2.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-YTJNT7DU.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-HRU6DDCH.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/kanban-definition-NDS4AKOZ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/gitGraphDiagram-7IBYFJ6S.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-TYCBKAJE.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/c4Diagram-VJAJSXHY.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/timeline-definition-BDJGKUSR.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-D6G4REZN.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/diagram-VNBRO52H.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-A2AXSNBT.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-VV3M67IP.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/stateDiagram-DGXRK772.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-C3MQ5ANM.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/sequenceDiagram-X6HHIX6F.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-7B677QYD.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-XZIHB7SX.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/sankeyDiagram-QLVOVGJD.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/dagre-OKDRZEBW.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/pieDiagram-IB7DONF6.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-O4NI6UNU.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/requirementDiagram-KVF5MWMF.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-AEK57VVT.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/stateDiagram-v2-YXO3MK2T.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-K557N5IZ.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/quadrantDiagram-7GDLP6J5.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/classDiagram-v2-COTLJTTW.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-4BMEZGHF.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/mindmap-definition-ALO5MXBD.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/flowDiagram-4HSFHLVR.mjs.map",
            "libs/third_party/mermaid/dist/chunks/mermaid.core/chunk-IIMUDSI4.mjs.map",
            "libs/third_party/mermaid/dist/mermaid.esm.mjs.map",
            "libs/third_party/mermaid/dist/mermaid.min.js.map",
            "libs/third_party/mermaid/dist/mermaid.core.mjs.map",
        ],
        icon: path.join(__dirname, './assets/app_icon/icon'),
    },
    rebuildConfig: {},
    makers: [
        {
            name: '@electron-forge/maker-zip',
            config: {},
        },
        {
            name: '@electron-forge/maker-squirrel',
            config: {},
        },
    ],
    electronRebuildConfig: {
        onlyModules: [],
        force: false,
        offline: true
    },
    plugins: [
        {
            name: '@electron-forge/plugin-auto-unpack-natives',
            config: {},
        },
        // Fuses are used to enable/disable various Electron functionality
        // at package time, before code signing the application
        new FusesPlugin({
            version: FuseVersion.V1,
            [FuseV1Options.RunAsNode]: false,
            [FuseV1Options.EnableCookieEncryption]: true,
            [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
            [FuseV1Options.EnableNodeCliInspectArguments]: false,
            [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
            [FuseV1Options.OnlyLoadAppFromAsar]: true,
        }),
    ],
};
